name: wind-speed-data
dependencies:
  - python=3.9
  - pip
  - pip:
    - opencv-python
    - torch
  - conda
  - conda:
    - ipykernel 
    - pandas
    - numpy
    - matplotlib
    - boto3
    - s3fs
    - seaborn